# Generated by Django 5.2.4 on 2025-08-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economycar',
            name='name',
        ),
        migrations.RemoveField(
            model_name='luxurycar',
            name='name',
        ),
        migrations.RemoveField(
            model_name='othercar',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pickupcar',
            name='name',
        ),
        migrations.RemoveField(
            model_name='suvcar',
            name='name',
        ),
        migrations.AddField(
            model_name='economycar',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='economycar',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='luxurycar',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='luxurycar',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='othercar',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='othercar',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pickupcar',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pickupcar',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suvcar',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suvcar',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
