# Generated by Django 5.2.4 on 2025-08-04 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_economycar_brand_alter_economycar_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luxurycar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='othercar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pickupcar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='suvcar',
            name='user',
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_day', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('available', models.BooleanField(default=True)),
                ('rented', models.BooleanField(default=False)),
                ('rent_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_type', models.CharField(choices=[('luxury', 'Luxury'), ('economy', 'Economy'), ('suv', 'SUV'), ('pickup', 'Pick Up'), ('other', 'Other')], default='other', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EconomyCar',
        ),
        migrations.DeleteModel(
            name='LuxuryCar',
        ),
        migrations.DeleteModel(
            name='OtherCar',
        ),
        migrations.DeleteModel(
            name='PickUpCar',
        ),
        migrations.DeleteModel(
            name='SUVCar',
        ),
    ]
