# Generated by Django 5.2.4 on 2025-08-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_luxurycar_user_remove_othercar_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='number_of_cars',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
