# Generated by Django 5.2.4 on 2025-08-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='cars_rented',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
