# Generated by Django 5.2.4 on 2025-08-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_history_cars_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(default='petrol', max_length=15),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=5),
        ),
    ]
