# Generated by Django 5.2.4 on 2025-08-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_car_fuel_car_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
