# Generated by Django 5.2.4 on 2025-08-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='rented',
        ),
    ]
