# Generated by Django 5.2.4 on 2025-08-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_car_rented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
    ]
