# Generated by Django 5.2.4 on 2025-08-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_car_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
