# Generated by Django 5.2.4 on 2025-08-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_user_info_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='rented',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
