# Generated by Django 5.2.4 on 2025-08-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_history_rented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='rented',
        ),
    ]
