# Generated by Django 5.2.4 on 2025-08-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_history_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='new_rented',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
