# Generated by Django 5.2.4 on 2025-08-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_history_new_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='card_number',
            field=models.IntegerField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='card_picture',
            field=models.FilePathField(default='static/card/VISA.png', path='static/card', recursive=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='card_type',
            field=models.CharField(choices=[('mastercard', 'Mastercard'), ('visa', 'VISA')], default='visa', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('luxury', 'Luxury'), ('economy', 'Economy'), ('suv', 'SUV'), ('pickup', 'Pick Up'), ('other', 'Other')], default='economy', max_length=20),
        ),
    ]
