# Generated by Django 5.2.4 on 2025-08-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_user_info_card_number_user_info_card_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='card_type',
            field=models.CharField(choices=[('visa', 'VISA'), ('mastercard', 'Mastercard')], default='visa', max_length=20),
        ),
    ]
